### ISSUE TITLE
The text on /apply page should be changed

### ISSUE THREAD

**Issue by reederz** [fadeit/fadeitdk#31]
"First of all, congrats on cracking that piece of code. We're excited to know that you are curious and willing to explore. We are always looking for a motivated and determined person to join our team. " - there's no code to crack anymore- the page is linked to from /team page.

**Comment by dandaniel** [comment]
"APPLY_WELCOME": "Hi there, stranger",
    "APPLY_TEXT_1": "Thanks for dropping by. We're excited to know that you are curious and willing to explore. We are always looking for a motivated and determined person to join our team." ?

**Comment by reederz** [comment]
Yeah, I think it's good.
