### ISSUE TITLE
Update 'da' text

### ISSUE THREAD

**Issue by danmindru** [fadeit/fadeitdk#42]
'Som udvikler er det vores job at sikre at visse regler overholdes når vi bygger 
software til vores kunder. For at sikre at vi ikke går på kompromis med vores 
regelsæt har vi som udgangspunkt altid én udvikler der læser koden igennem 
inden den bliver frigivet.'

**Comment by reederz** [comment]
How about:
Det er vores job at sikre at visse regler overholdes når vi bygger
software til vores kunder. For at sikre at vi ikke går på kompromis med vores
regelsæt har vi som udgangspunkt altid manuel og automatisk acceptance testing procedurer på plads.

**Comment by danmindru** [comment]
:+1: 
Remember to check this with Lars and update it @reederz :)
