### ISSUE TITLE
Figure out how to block spam hits to our page

### ISSUE THREAD

**Issue by reederz** [fadeit/fadeitdk#48]
The majority of hits to our website comes from shady sources which makes it hard to make sense of analytics.

**Comment by danmindru** [comment]
#32 related

**Comment by reederz** [comment]
Totally forgot. I'll take care of it.

**Comment by reederz** [comment]
I made a blacklist.conf in our nginx server with bad user agents, ip ranges and referrers to filter out some bad bots, spam referral bots, pentest scanners, surveillance bots, etc. We can make additional entries in the blacklist as we go along.

**Comment by reederz** [comment]
I'll deploy it in a couple of days once Sander's done with his crawling.
