### ISSUE TITLE
Going to /blog should probably set the language to english

### ISSUE THREAD

**Issue by danmindru** [fadeit/fadeitdk#71]
English-readers will have a danish menu with no way to switch.

If it's not saved to local storage it shouldn't cause any problems.

**Comment by reederz** [comment]
+1

**Comment by ozooner** [comment]
The blog will remember your previous language is you've visited page before, else it defaults to english (always been like so). if you open incognito and go directly to fadeit.dk/blog, then you will see English menu. 
Whereas if you go to fadeit.dk it will default to danish and if from there navigate to blog, it will keep language setting.
