### ISSUE TITLE
Consider moving to github pages

### ISSUE THREAD

**Issue by reederz** [fadeit/fadeitdk#72]
https://pages.github.com/

Is there anything that would prevent us from doing it @ozooner @danmindru ? Otherwise, I don't see a point for hosting the site.

**Comment by danmindru** [comment]
We use nginx to redirect crawlers to _escaped-fragment_= pages & to load index.html for any request. There's more logic too, for example setting the response status to 404 (because all pages will return index.html, there's no way to detect not found pages on the front), etc...
