### ISSUE TITLE
JSON code blocks wont't render in blog posts

### ISSUE THREAD

**Issue by reederz** [fadeit/fadeitdk#73]
I have the following *block.json* file:

```json
{
  "some": "shit"
}
```

Subsequently, I include it in my blog post:

```json
{
  "type": "code",
  "language": "bash",
  "file": "block.json"
}
```

The end result:
![dammit](https://cloud.githubusercontent.com/assets/3193560/8509285/eb3eb864-229b-11e5-8e34-1f878c9684fd.png)

**Comment by reederz** [comment]
I can only render it if I make it invalid JSON

**Comment by reederz** [comment]
I can fix it myself, if you're not up for it @danmindru

**Comment by danmindru** [comment]
Can you try file.json.txt?

**Comment by reederz** [comment]
Tried

**Comment by danmindru** [comment]
Still remember to use the `.txt` extension cuz grunt is treating JSON files as data (we use them for projects, expertise, etc)

**Comment by danmindru** [comment]
Is this still relevant? I forgot.

**Comment by reederz** [comment]
Yes, still relevant. Though it's not critical because I've found a workaround I.e. make a barely visible syntax error like a *`* (backtick) at the end of the file.
