### ISSUE TITLE
Apply page redirect to thank you not working

### ISSUE THREAD

**Issue by danmindru** [fadeit/fadeitdk#75]
@ozooner have any idea how it got broken?

Seems the form action is from back in the hashbang days. 
https://www.dropbox.com/s/jfe8vcqg71fev73/Screenshot%202015-09-01%2022.17.52.png?dl=0

Can we just redirect from the controller? 
https://github.com/fadeit/fadeitdk/blob/master/src/app/apply/apply.controller.js

**Comment by ozooner** [comment]
It was due to drupal site at danmind.ru/api redirecting to that page after form submission. Now it will redirect to http://fadeit.dk/thanks
