### ISSUE TITLE
Update team page / unique URL

### ISSUE THREAD

**Issue by danmindru** [fadeit/fadeitdk#83]

**Comment by reederz** [comment]
Still relevant?

**Comment by danmindru** [comment]
It's complicated.
What I had in mind is something similar to https://fadeit.dk/blog/authors/justas/, but combined with the metadata at fadeit.dk/team (that was when the blog wasn't running Jekyll, so we could be consistent between the team page and blog). 
It's a hairy situation atm, because we don't want to spend time syncing fadeit.dk/team with fadeit.dk/blog.
Perhaps the right thing to do is just to link to the jekyll author page for those that have it.
Feel free to decide on it ;)
