### ISSUE TITLE
Can't load 'apply form' because of HTTPS

### ISSUE THREAD

**Issue by danmindru** [fadeit/fadeitdk#93]
Roll a script to replace it or suffer the consequences @reederz 
It's on {host}/da/apply

**Comment by reederz** [comment]
@danmindru I've added the form directly into the app and built the backend for it, which is running on our server. Can you do input validation (name, email required) and success, failure feedback?

**Comment by danmindru** [comment]
Don't you wanna add a field for website/github? Otherwise good to go.

**Comment by reederz** [comment]
@danmindru Regarding fields - no, I don't think so. To make it even more generic, we could remove the education field. Can you do it in frontend? I'll take care of the backend.

**Comment by reederz** [comment]
All good now. Closing the issue.
